#!/usr/bin/python
# 
# Version      : 1.0
# Description  : This script is a basic bot to login to stackexchange account (only) on your machine running python. Only tested on OSX
# Author       : nosweat 
# Date         : 19/12/2015
# Dependencies : requests (https://github.com/kennethreitz/requests)
# Notes: please refer here on how to run this script on MAC OSX :
# http://stackoverflow.com/questions/9522324/running-python-in-background-on-os-x

import requests, time, sys, getopt, os, os.path
from HTMLParser import HTMLParser
from htmlentitydefs import name2codepoint
from datetime import datetime, timedelta

false = False # alias
true = True   # alias
one_hour = 3600 # constant
pid_path = '/tmp/stacklogin.pid' #path of the pid

# ======================================================
# BASIC CONFIGURATIONS
# ======================================================
so_email = ''           # your stackexchange email
so_password = ''        # your stackexchange password
so_login_frequency = 1  # login frequency in hours; defaults to every hour

class style:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

class stackOverflow():

    base_url = 'https://stackoverflow.com/users/login?ssrc=head'
    fkey = ''

    def __init__(self):
        self.fkey = self.getFkey()

    # Login method that sends POST Request to the stackoverflow auth server
    def doLogin(self):
        print "Authenticating request..."
        payload = self.getPayload()
        payload['fkey'] = self.fkey
        r = requests.post(self.base_url, data=payload,headers=self.getHeaders())
        print "[ Logged in ]:", self.fkey

    # Construct Payload being sent to the Stackoverflow server
    def getPayload(self):
        payload = {\
            'email' : so_email,\
            'password' : so_password,\
            'isSignup' : false,\
            'isLogin' : true,\
            'isPassword' : false,\
            'isAddLogin' : false,\
            'hasCaptcha' : false,\
            'fkey' : '',\
            'ssrc' : 'head',\
            'submitbutton' : 'Log in',\
            'oauthversion' : '',\
            'oauthserver' : '',\
            'openidusername' : '',\
            'openididentifier' : ''}
        return payload

    # Create Header information for stackoverflow-specific request
    def getHeaders(self):
        return {'Content-type':'application/x-www-form-urlencoded'}

    # Send a GET request to Stackoverflow to create Fkey for CSRF purposes
    def getFkey(self):
        print "Retrieving fkey information..."
        r = requests.get(self.base_url, params=self.getPayload(), headers=self.getHeaders())
        parser = customHTMLParser()
        parser.feed(r.text)
        return parser.fkey

class customHTMLParser(HTMLParser):

    isFkeyFlag = false
    fkey = ''

    def handle_starttag(self, tag, attrs):
        for name, value in attrs:
            ##print "    attrs:", name, value
            if name == 'name' and value == 'fkey':
                self.isFkeyFlag = True

            if name == 'value' and self.isFkeyFlag:
                self.fkey = value
                ##print "    Fkey:", self.fkey
                self.isFkeyFlag = False
                break

    def handle_endtag(self, tag):
        ##print "End tag  :", tag
        h = ''

    def handle_data(self, data):
        ##print "Data     :", data
        h = ''

    def handle_comment(self, data):
        ##print "Comment  :", data
        h = ''

    def handle_entityref(self, name):
        c = unichr(name2codepoint[name])
        ##print "Named ent:", c

    def handle_charref(self, name):
        if name.startswith('x'):
            c = unichr(int(name[1:], 16))
        else:
            c = unichr(int(name))
        ##print "Num ent  :", c

    def handle_decl(self, data):
        ##print "Decl     :", data
        h = ''
class process():
    @staticmethod
    def pid():
        try:
            f = open(pid_path,'w')
            f.write(format(datetime.now(), '%D%H%M%S'))
            f.close()
        except Exception as e:
            print "Error: Unable to write pid \n", e
    
    @staticmethod
    def isRunning():
        return os.path.exists(pid_path) and os.path.isfile(pid_path)

def main(argv):
    _key_found = 0
    so_login_frequency = 1
    status = False
    helper = '\n' + style.BOLD  + '[Usage]' + style.END +': stacklogin [--options]\n' + style.BOLD +'\n Options: '+ style.END +'\n\
      -h               = help flag to show this options\n\
      -u, --username   = stackexchange email\n\
      -p, --password   = stackexchange password\n\
      -f, --frequency  = login frequency in hours\n\
      -s, --status     = a flag argument to determine the status of the script whether running or not running'
    
    try:
        opts, args = getopt.getopt(argv,"hu:p:f:s",["username=","password=","frequency=","status"])
    except getopt.GetoptError:
        print style.BOLD + "Error:" + style.END +" wrong command arguments\n", helper
        sys.exit(2)
    
    for opt, arg in opts: 
        if opt == '-h':
            print helper
            sys.exit()
        elif opt in ("-u", "--username"):
            so_email = arg
        elif opt in ("-p", "--password"):
            so_password = arg
        elif opt in ("-f", "--frequency"):
            try:
                so_login_frequency = int(arg)
            except:
                print 'Error: not valid frequency (-f) format, expects integer'
                sys.exit(2)
        elif opt in ("-s", "--status"):
            status = True
            _key_found = 1
            break
        _key_found = 1

    if _key_found == 0 :
        print 'Error: Missing `-u`|`--username` `-p`|`--password` argument ';	  
        sys.exit()
    if status:
        if process.isRunning():
            print 'Stacklogin is running.'
        else:
            print 'Stacklogin is not running.'
    
    try:
        if 'so_email' in locals() and 'so_password' in locals():
            #create process id
            process.pid()
            while True:
                so = stackOverflow()
                so.doLogin()
                nextLogin = (so_login_frequency * one_hour) / one_hour 
                setupHours = datetime.now() + timedelta(hours=nextLogin)
                print "Next Login in " + format(setupHours, '%H:%M:%S')
                time.sleep(so_login_frequency * one_hour)
        elif status:
            print ""
        else:
            print "Unable to authenticate"
    except:
        try:
            os.remove(pid_path)
        except:
            pass
        print "Process ended"

if __name__ == "__main__":
   main(sys.argv[1:])
   
#EOF